# Copyright Luc ROBERT--VILLANUEVA 2026
# Distributed under the Boost Software License, Version 1.0
# (See accompanying file LICENSE or copy at https://www.boost.org/LICENSE_1_0.txt)

import struct
import sys

with open(sys.argv[1], "rb") as f:
    data = f.read()

assert data[:4] == b"\x72\xb5\x4a\x86", "PSF2 magic not found"

version = struct.unpack_from("<I", data, 4)[0]
header_size = struct.unpack_from("<I", data, 8)[0]
flags = struct.unpack_from("<I", data, 12)[0]
num_glyphs = struct.unpack_from("<I", data, 16)[0]
charsize = struct.unpack_from("<I", data, 20)[0]

HAS_UNICODE_TABLE = 0x01
has_unicode = bool(flags & HAS_UNICODE_TABLE)

glyphs_data = data[header_size : header_size + num_glyphs * charsize]

cp_to_glyph: dict[int, int] = {}

if has_unicode:
    unicode_table = data[header_size + num_glyphs * charsize :]
    glyph_idx = 0
    i = 0
    while i < len(unicode_table) and glyph_idx < num_glyphs:
        while i < len(unicode_table):
            b = unicode_table[i]
            if b == 0xFF:
                i += 1
                glyph_idx += 1
                break
            elif b == 0xFE:
                i += 1
            else:
                if b < 0x80:
                    cp = b
                    i += 1
                elif b < 0xE0:
                    cp = ((b & 0x1F) << 6) | (unicode_table[i + 1] & 0x3F)
                    i += 2
                elif b < 0xF0:
                    cp = (
                        ((b & 0x0F) << 12)
                        | ((unicode_table[i + 1] & 0x3F) << 6)
                        | (unicode_table[i + 2] & 0x3F)
                    )
                    i += 3
                else:
                    cp = (
                        ((b & 0x07) << 18)
                        | ((unicode_table[i + 1] & 0x3F) << 12)
                        | ((unicode_table[i + 2] & 0x3F) << 6)
                        | (unicode_table[i + 3] & 0x3F)
                    )
                    i += 4
                if cp < 256 and cp not in cp_to_glyph:
                    cp_to_glyph[cp] = glyph_idx
else:
    for idx in range(min(num_glyphs, 256)):
        cp_to_glyph[idx] = idx

print("//! GENERATED BY `../scripts/font.py` DO NOT EDIT")
print()
print("pub const data: [256][16]u8 = .{")
for cp in range(256):
    glyph_idx = cp_to_glyph.get(cp)
    if glyph_idx is not None and glyph_idx < num_glyphs:
        raw = glyphs_data[glyph_idx * charsize : glyph_idx * charsize + charsize]
        glyph = (raw + b"\x00" * 16)[:16]
    else:
        glyph = b"\x00" * 16
    row = ", ".join(f"0x{b:02X}" for b in glyph)
    comment = f" // '{chr(cp)}'" if 0x20 <= cp <= 0x7E else f" // 0x{cp:02X}"
    print(f"    .{{ {row} }},{comment}")
print("};")
